# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bolg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PythonAdmin',
            new_name='Django',
        ),
        migrations.RenameModel(
            old_name='DjangoAdmin',
            new_name='Python',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterModelOptions(
            name='django',
            options={'verbose_name': 'Django', 'verbose_name_plural': 'Django'},
        ),
        migrations.AlterModelOptions(
            name='python',
            options={'verbose_name': 'Python', 'verbose_name_plural': 'Python'},
        ),
    ]
